### ISSUE TITLE
Java Inheritance I 

### ISSUE THREAD

**Issue by Rittika1234** [Riddhi9570/HackerrankPracticeProblems#67] opened 2022-10-01 06:56 UTC
write your solution to this java problem of hackerrank:-
Problem link: https://www.hackerrank.com/challenges/java-inheritance-1/problem

**Comment by Rittika1234** [comment] 2022-10-01 06:56
can you please assign me this issue for hacktoberfest?

**Comment by sahilsarawagi** [comment] 2022-10-02 05:32
please assign this to me for hacktoberfest.

**Comment by Riddhi9570** [comment] 2022-10-02 08:32
@sahilsarawagi 
Hey, Thanks for raising an issue!
Nice to know that you are eager for the contribution😃!
Please note that it is considered a good practice to first wait till the issue is assigned to you, before working on it.

**Closed** 2022-10-02 08:34 UTC
Labels: good first issue, hacktoberfest, up-for-grab
