### ISSUE TITLE
Java: Java Datatypes

### ISSUE THREAD

**Issue by Anjali2201** [Riddhi9570/HackerrankPracticeProblems#127] opened 2022-10-01 16:03 UTC
Problem Link:
https://www.hackerrank.com/challenges/java-datatypes/problem?isFullScreen=true

Problem is already solved by me. Just have to upload it. Could you assign it to me?

**Comment by Riddhi9570** [comment] 2022-10-01 17:15
@Anjali2201 
Hey, Thanks for raising an issue!
Unfortunately, this problem statement has already been raised in another issue #26. 
You may take another hackerrank problem, raise an issue and make a PR only when it gets assigned to you.
Thanks! Happy Coding😃!

**Comment by Anjali2201** [comment] 2022-10-01 17:33
I have added one more practice problem of python: arithmetic operator in the same pr. I guess that question is still not solved. Should i raise another issue?

**Comment by Riddhi9570** [comment] 2022-10-01 17:38
Sorry, that problem is also raised in issue #37. Please make sure that the problem is not already raised in an issue or present in the repo. Once you have checked, you can raise a new issue. Thanks!

**Comment by Riddhi9570** [comment] 2022-10-01 17:40
Also, please delete the commit you made earlier before making a new PR.

**Closed** 2022-10-01 17:41 UTC
