### ISSUE TITLE
C++: lower_bound-stl

### ISSUE THREAD

**Issue by KshshVrma** [Riddhi9570/HackerrankPracticeProblems#150] opened 2022-10-02 05:10 UTC
### Hackerrank problem link

Provide your hackerrank problem link here.
https://www.hackerrank.com/challenges/cpp-lower-bound/problem?isFullScreen=true
### Issue Checklist

* [ X] If you have previously contributed to this repo, you declare that you have not made a pull request for more than one issue in this repo till now.
* [ X] Your forked repo is up-to-date with the the origin remote.
* [ X] Have you checked that the hackerrank problem you are raising is not already present in the repo?
* [X ] Have you checked that the hackerrank problem you are raising is not raised by or assigned to another contributor?

### Hacktoberfest Contributor

* [ X] Are you a Hacktoberfest Contributor?

### Any other Changes?

If you are raising an issue with some more changes, please provide the details here.

**Comment by Riddhi9570** [comment] 2022-10-02 08:24
@KshshVrma 
Hey, Thanks for raising an issue!
Nice to know that you are eager for the contribution😃!
Please note that It is considered a good practice to first wait till the issue is assigned to you, before working on it.

**Closed** 2022-10-02 08:27 UTC
Labels: hacktoberfest
