### ISSUE TITLE
Basic standard data structures

### ISSUE THREAD

**Issue by Rohan-G** [Riddhi9570/HackerrankPracticeProblems#55] opened 2022-10-01 04:41 UTC
Hey @Riddhi9570,
would it be a good idea to add basic data structures like stacks and queues for each language, and if so, could I work on one of the C++ ones.

**Comment by Riddhi9570** [comment] 2022-10-01 06:26
@Rohan-G Do you mean hackerrank problems from those topics or something else? Please elaborate.

**Comment by Rohan-G** [comment] 2022-10-01 08:35
@Riddhi9570 yep hackerrank problems like the ones you've added for the basic conditional statements and loops and stuff

**Comment by Riddhi9570** [comment] 2022-10-01 09:02
@Rohan-G Go ahead, mention the problem link you would like to work on, in the issue , and start working once the issue is assigned to you.

**Closed** 2022-10-01 19:53 UTC
